
package ru.myCompany.siebel.ws.getClientInfo.userInterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "spcIntegration", targetNamespace = "http://siebel.com/CustomUI", wsdlLocation = "file:/C:/Java/jdk1.8.0_45/bin/siebel_6685_small.wsdl")
public class SpcIntegration
    extends Service
{

    private final static URL SPCINTEGRATION_WSDL_LOCATION;
    private final static WebServiceException SPCINTEGRATION_EXCEPTION;
    private final static QName SPCINTEGRATION_QNAME = new QName("http://siebel.com/CustomUI", "spcIntegration");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Java/jdk1.8.0_45/bin/siebel_6685_small.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPCINTEGRATION_WSDL_LOCATION = url;
        SPCINTEGRATION_EXCEPTION = e;
    }

    public SpcIntegration() {
        super(__getWsdlLocation(), SPCINTEGRATION_QNAME);
    }

    public SpcIntegration(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPCINTEGRATION_QNAME, features);
    }

    public SpcIntegration(URL wsdlLocation) {
        super(wsdlLocation, SPCINTEGRATION_QNAME);
    }

    public SpcIntegration(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPCINTEGRATION_QNAME, features);
    }

    public SpcIntegration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpcIntegration(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetClientInfo
     */
    @WebEndpoint(name = "GetClientInfo")
    public GetClientInfo getGetClientInfo() {
        return super.getPort(new QName("http://siebel.com/CustomUI", "GetClientInfo"), GetClientInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetClientInfo
     */
    @WebEndpoint(name = "GetClientInfo")
    public GetClientInfo getGetClientInfo(WebServiceFeature... features) {
        return super.getPort(new QName("http://siebel.com/CustomUI", "GetClientInfo"), GetClientInfo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPCINTEGRATION_EXCEPTION!= null) {
            throw SPCINTEGRATION_EXCEPTION;
        }
        return SPCINTEGRATION_WSDL_LOCATION;
    }

}
